<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Elements\Background_Clicker.png" />
    <None Remove="Elements\Background_Credits.png" />
    <None Remove="Elements\Background_Puzzle.png" />
    <None Remove="Elements\Background_start.png" />
    <None Remove="Elements\dialogue_window.png" />
    <None Remove="Elements\Logo.png" />
    <None Remove="Elements\next_button.png" />
    <None Remove="Res\.png" />
    <None Remove="Res\A_angry.PNG" />
    <None Remove="Res\A_neutral.PNG" />
    <None Remove="Res\A_sad.PNG" />
    <None Remove="Res\Background_Bad.png" />
    <None Remove="Res\Background_Best.PNG" />
    <None Remove="Res\Background_Blackout.png" />
    <None Remove="Res\Background_Bus.png" />
    <None Remove="Res\Background_Discord.png" />
    <None Remove="Res\Background_Door.png" />
    <None Remove="Res\Background_Door_Light.png" />
    <None Remove="Res\Background_Good.png" />
    <None Remove="Res\Background_Holl.png" />
    <None Remove="Res\Background_Lecture.png" />
    <None Remove="Res\Background_Polegon.png" />
    <None Remove="Res\Background_Secret.png" />
    <None Remove="Res\Background_Zlata_Room.png" />
    <None Remove="Res\choices_back.png" />
    <None Remove="Res\choice_button.png" />
    <None Remove="Res\MaxAlexTogether.png" />
    <None Remove="Res\M_angry.PNG" />
    <None Remove="Res\M_neutral.PNG" />
    <None Remove="Res\M_sad.PNG" />
    <None Remove="Res\V_angry.PNG" />
    <None Remove="Res\V_happy.PNG" />
    <None Remove="Res\V_neutral.PNG" />
    <None Remove="Res\V_sad.PNG" />
    <None Remove="Res\ZlataValTogether.png" />
    <None Remove="Res\ZlataValTogether_happy.PNG" />
    <None Remove="Res\ZlataValTogether_sad.png" />
    <None Remove="Res\Z_angry.PNG" />
    <None Remove="Res\Z_happy.PNG" />
    <None Remove="Res\Z_neutral.PNG" />
    <None Remove="Res\Z_sad.PNG" />
    <None Remove="Res\кунзик.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Elements\Background_Clicker.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Elements\Background_Credits.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Elements\Background_Puzzle.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Elements\Background_start.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Elements\dialogue_window.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Elements\Logo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Elements\next_button.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\A_angry.PNG">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\A_neutral.PNG">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\A_sad.PNG">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Elements\choice_button.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\Background_Bad.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\Background_Blackout.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\Background_Bus.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\Background_Discord.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\Background_Door.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\Background_Door_Light.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\Background_Good.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\Background_Holl.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\Background_Lecture.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\Background_Polegon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\Background_Secret.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\Background_Zlata_Room.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\Background_Best.PNG">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\MaxAlexTogether.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\M_angry.PNG">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\M_neutral.PNG">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\M_sad.PNG">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\V_sad.PNG">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Res\.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\choices_back.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\V_angry.PNG">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\V_happy.PNG">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\V_neutral.PNG">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\ZlataValTogether_happy.PNG">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\ZlataValTogether_sad.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\Z_angry.PNG">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\Z_happy.PNG">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\Z_neutral.PNG">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\Z_sad.PNG">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Res\кунзик.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Res\characters.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="scenes\scenes.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
